
export const FOLLOWED = 'FOLLOWED'
export const UNFOLLOWED = 'UNFOLLOWED'
export const SET_USERS = 'SET-USERS'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_TOTAL_USER_COUNT = 'SET_TOTAL_USER_COUNT'
export const DISPLAY_LOADING_SCREEN = 'DISPLAY_LOADING_SCREEN'